import fs from 'fs';
import path from 'path';

// Complete dictionary of all 58 Medical Specialties
const SPECIALTY_DEFINITIONS = [
  // 1. Cardiology
  {
    id: "SPEC-CARD-001", parent_id: null, specialty_code: "CARD", specialty_name: "Cardiology",
    official_name: "Cardiovascular Medicine", display_name: "Cardiology",
    category: ["CLINICAL", "DIAGNOSTIC"], specialty_level: 1, parent_specialty: null,
    description: "Diagnosis, medical management, and prevention of heart and circulatory vascular diseases.",
    clinical_scope: ["Ischemic heart disease", "Heart failure", "Arrhythmias", "Valvular diseases", "Hypertension", "Dyslipidemias"],
    organ_system: ["Cardiovascular System"], body_system: ["Circulatory System"],
    anatomical_regions: ["Heart", "Myocardium", "Pericardium", "Coronary Arteries", "Aorta"],
    primary_functions: ["Circulation", "Perfusion", "Electrophysiology", "Myocardial contraction"],
    common_conditions: ["Essential Hypertension", "Coronary Artery Disease", "Heart Failure", "Atrial Fibrillation", "Aortic Stenosis"],
    major_diseases: ["Acute Myocardial Infarction", "Dilated Cardiomyopathy", "Infective Endocarditis", "Ventricular Tachycardia"],
    common_symptoms: ["Chest Pain", "Dyspnea on exertion", "Palpitations", "Syncope", "Leg Edema"],
    diagnostic_tests: ["12-Lead ECG", "2D Echocardiogram", "TMT Stress Test", "Holter Monitor", "Coronary CT Angiography"],
    laboratory_tests: ["High-Sensitivity Troponin", "NT-proBNP / BNP", "Lipid Profile Panel", "CK-MB"],
    imaging_tests: ["Coronary Angiogram", "Cardiac MRI", "Echocardiography", "SPECT Myocardial Perfusion"],
    procedures: ["Percutaneous Coronary Intervention", "Coronary Angiography", "Cardioversion"],
    treatments: ["Antiplatelets", "Anticoagulants", "Beta-blockers", "ACE inhibitors/ARBs", "Statins"],
    medications_or_drug_classes: ["Statins", "Beta-Blockers", "ACE-Inhibitors", "ARBs", "NOACs", "Antiplatelets"],
    surgical_procedures: [], emergency_conditions: ["STEMI", "Cardiogenic Shock", "Ventricular Fibrillation", "Cardiac Arrest"],
    related_specialties: ["Cardiothoracic Surgery", "Electrophysiology", "Vascular Surgery"],
    sub_specialties: ["Interventional Cardiology", "Electrophysiology", "Heart Failure & Transplant"],
    referral_specialties: ["Cardiothoracic Surgery", "Nephrology", "Endocrinology"],
    doctor_title: "Cardiologist", department_name: "Department of Cardiology", hospital_department: "Cardiology & CCU",
    search_keywords: ["heart doctor", "cardiac specialist", "chest pain doctor", "heart attack doctor", "bp specialist"],
    synonyms: ["Cardiovascular Medicine", "Cardiac Medicine", "Heart Care"], abbreviations: ["CARD", "CV"],
    alternative_names: ["Adult Cardiology", "Clinical Cardiology"], common_misspellings: ["cardology", "cardiologie"],
    ICD_related_terms: ["I20-I25", "I50", "I48"], SNOMED_related_terms: ["394579002"], LOINC_related_terms: ["8867-4"],
    medical_report_types: ["ECG Traces", "2D Echo Reports", "Coronary Angiography", "Holter Reports", "Cardiac Biomarkers"],
    supported_document_types: ["PDF", "JPG", "PNG", "DICOM"], is_clinical: true, is_diagnostic: true, is_surgical: false, is_laboratory: false, is_imaging: true, is_primary_care: false, is_subspecialty: false, is_active: true
  },
  // 2. Neurology
  {
    id: "SPEC-NEUR-002", parent_id: null, specialty_code: "NEUR", specialty_name: "Neurology",
    official_name: "Neurological Medicine", display_name: "Neurology",
    category: ["CLINICAL", "DIAGNOSTIC"], specialty_level: 1, parent_specialty: null,
    description: "Management of disorders of the brain, spinal cord, cranial nerves, peripheral nerves, and muscles.",
    clinical_scope: ["Stroke", "Epilepsy", "Neurodegeneration", "Headaches", "Neuromuscular diseases", "Multiple Sclerosis"],
    organ_system: ["Nervous System"], body_system: ["Central & Peripheral Nervous System"],
    anatomical_regions: ["Cerebrum", "Cerebellum", "Brainstem", "Spinal Cord", "Peripheral Nerves"],
    primary_functions: ["Cognition", "Motor control", "Sensory perception", "Autonomic regulation"],
    common_conditions: ["Migraine", "Ischemic Stroke", "Epilepsy", "Parkinson's Disease", "Multiple Sclerosis", "Neuropathy"],
    major_diseases: ["Alzheimer's Dementia", "Amyotrophic Lateral Sclerosis", "Guillain-Barré Syndrome", "Intracranial Hemorrhage"],
    common_symptoms: ["Severe Headache", "Seizures", "Weakness / Paralysis", "Numbness", "Tremors", "Ataxia"],
    diagnostic_tests: ["Electroencephalogram (EEG)", "Electromyography (EMG)", "Nerve Conduction Studies (NCS)", "Lumbar Puncture"],
    laboratory_tests: ["CSF Analysis", "Autoantibody Panels", "Serum B12", "Anti-AChR Antibodies"],
    imaging_tests: ["MRI Brain & Spine", "CT Brain", "MR Angiography (MRA)", "Carotid Doppler"],
    procedures: ["Lumbar Puncture", "Therapeutic Botox", "EEG Monitoring"],
    treatments: ["Thrombolysis (IV rtPA)", "Anticonvulsants", "Dopaminergic agents", "Immunomodulators"],
    medications_or_drug_classes: ["Antiepileptics", "Levodopa", "Triptans", "Monoclonal Antibodies"],
    surgical_procedures: [], emergency_conditions: ["Acute Ischemic Stroke", "Status Epilepticus", "Bacterial Meningitis"],
    related_specialties: ["Neurosurgery", "Psychiatry", "Radiology", "Physical Medicine & Rehabilitation"],
    sub_specialties: ["Stroke / Vascular Neurology", "Epileptology", "Movement Disorders", "Neuro-Immunology"],
    referral_specialties: ["Neurosurgery", "Ophthalmology", "Rheumatology"],
    doctor_title: "Neurologist", department_name: "Department of Neurology", hospital_department: "Neurology & Stroke Care Unit",
    search_keywords: ["brain doctor", "nerve specialist", "stroke specialist", "epilepsy doctor", "headache specialist"],
    synonyms: ["Neurological Medicine", "Neuroscience", "Brain Medicine"], abbreviations: ["NEUR", "NEURO"],
    alternative_names: ["Clinical Neurology"], common_misspellings: ["neurolagy", "neuorology"],
    ICD_related_terms: ["G40", "G43", "I63", "G20"], SNOMED_related_terms: ["394591006"], LOINC_related_terms: ["18751-8"],
    medical_report_types: ["MRI Brain Reports", "CT Head Scans", "EEG Traces", "EMG/NCS Reports"],
    supported_document_types: ["PDF", "JPG", "PNG", "DICOM"], is_clinical: true, is_diagnostic: true, is_surgical: false, is_laboratory: false, is_imaging: true, is_primary_care: false, is_subspecialty: false, is_active: true
  },
  // 3. Dermatology
  {
    id: "SPEC-DERM-003", parent_id: null, specialty_code: "DERM", specialty_name: "Dermatology",
    official_name: "Dermatology & Cutaneous Biology", display_name: "Dermatology",
    category: ["CLINICAL", "DIAGNOSTIC", "SURGICAL"], specialty_level: 1, parent_specialty: null,
    description: "Diagnosis, medical treatment, and procedural management of skin, hair, and nail disorders.",
    clinical_scope: ["Inflammatory dermatoses", "Cutaneous malignancies", "Infectious skin diseases", "Trichology", "Cosmetic dermatology"],
    organ_system: ["Integumentary System"], body_system: ["Integumentary System"],
    anatomical_regions: ["Epidermis", "Dermis", "Subcutis", "Hair Follicles", "Nails", "Sebaceous Glands"],
    primary_functions: ["Skin barrier defense", "Thermoregulation", "UV protection", "Sensation"],
    common_conditions: ["Acne Vulgaris", "Atopic Eczema", "Psoriasis", "Alopecia", "Onychomycosis", "Urticaria"],
    major_diseases: ["Melanoma", "Basal Cell Carcinoma", "Pemphigus Vulgaris", "Stevens-Johnson Syndrome"],
    common_symptoms: ["Skin Itching (Pruritus)", "Rashes", "Skin Lesions", "Pigmentation Changes", "Hair Loss"],
    diagnostic_tests: ["Dermoscopy", "Skin Punch/Shave Biopsy", "Wood's Lamp Exam", "Patch Testing"],
    laboratory_tests: ["Serum IgE", "Autoimmune Skin Antibodies", "Fungal KOH Mount & Culture"],
    imaging_tests: ["Confocal Microscopy", "High-Frequency Skin Ultrasound"],
    procedures: ["Cryotherapy", "Skin Biopsy", "Electrocautery", "Phototherapy"],
    treatments: ["Topical Corticosteroids", "Retinoids", "Biologics", "Antifungals", "Immunosuppressants"],
    medications_or_drug_classes: ["Topical Steroids", "Isotretinoin", "Biologics", "Antihistamines"],
    surgical_procedures: ["Mohs Micrographic Surgery", "Skin Tumor Excision", "Cyst Enucleation"],
    emergency_conditions: ["Toxic Epidermal Necrolysis", "Stevens-Johnson Syndrome", "Erythroderma"],
    related_specialties: ["Venereology", "Allergology", "Histopathology", "Plastic Surgery"],
    sub_specialties: ["Dermatopathology", "Pediatric Dermatology", "Mohs Procedural Dermatology"],
    referral_specialties: ["Allergology", "Rheumatology", "Oncology", "Plastic Surgery"],
    doctor_title: "Dermatologist", department_name: "Department of Dermatology", hospital_department: "Dermatology & Skin Clinic",
    search_keywords: ["skin doctor", "dermatologist", "acne doctor", "rash specialist", "hair fall doctor"],
    synonyms: ["Skin Medicine", "Cutaneous Medicine"], abbreviations: ["DERM"],
    alternative_names: ["Dermatology & Venereology"], common_misspellings: ["dermotology", "dermatolgy"],
    ICD_related_terms: ["L00-L99", "C43"], SNOMED_related_terms: ["394582007"], LOINC_related_terms: ["18752-6"],
    medical_report_types: ["Skin Biopsy Reports", "Dermoscopy Reports", "Patch Test Allergy Reports"],
    supported_document_types: ["PDF", "JPG", "PNG"], is_clinical: true, is_diagnostic: true, is_surgical: true, is_laboratory: false, is_imaging: false, is_primary_care: false, is_subspecialty: false, is_active: true
  },
  // 4. Gastroenterology
  {
    id: "SPEC-GAST-004", parent_id: null, specialty_code: "GAST", specialty_name: "Gastroenterology",
    official_name: "Gastroenterology & Digestive Diseases", display_name: "Gastroenterology",
    category: ["CLINICAL", "DIAGNOSTIC"], specialty_level: 1, parent_specialty: null,
    description: "Management of diseases of the gastrointestinal tract including esophagus, stomach, intestines, colon, and pancreas.",
    clinical_scope: ["GERD", "Peptic Ulcer", "Inflammatory Bowel Disease (IBD)", "Malabsorption", "Pancreatic disorders"],
    organ_system: ["Digestive System"], body_system: ["Gastrointestinal System"],
    anatomical_regions: ["Esophagus", "Stomach", "Duodenum", "Small Bowel", "Colon", "Rectum", "Pancreas"],
    primary_functions: ["Digestion", "Nutrient Absorption", "GI Motility", "Mucosal Defense"],
    common_conditions: ["GERD", "Peptic Ulcer Disease", "Irritable Bowel Syndrome (IBS)", "Ulcerative Colitis", "Crohn's Disease"],
    major_diseases: ["Acute/Chronic Pancreatitis", "Colorectal Cancer", "Celiac Disease", "GI Bleeding"],
    common_symptoms: ["Abdominal Pain", "Heartburn / Acid Reflux", "Dysphagia", "Chronic Diarrhea / Constipation", "Blood in Stool"],
    diagnostic_tests: ["Upper GI Endoscopy (OGD)", "Colonoscopy", "ERCP", "Endoscopic Ultrasound (EUS)"],
    laboratory_tests: ["Fecal Calprotectin", "Fecal Occult Blood", "Serum Amylase & Lipase", "tTG-IgA"],
    imaging_tests: ["Abdominal Ultrasound", "CT Abdomen & Pelvis", "MR Enterography", "Barium Studies"],
    procedures: ["Polypectomy", "Endoscopic Banding", "Esophageal Dilation", "Capsule Endoscopy"],
    treatments: ["PPIs", "5-ASAs", "Biologics", "Pancreatic Enzymes", "Prokinetics"],
    medications_or_drug_classes: ["Proton Pump Inhibitors", "Immunomodulators", "Anti-TNF Biologics"],
    surgical_procedures: [], emergency_conditions: ["Acute Upper GI Hemorrhage", "Acute Necrotizing Pancreatitis", "Toxic Megacolon"],
    related_specialties: ["Hepatology", "General Surgery", "Colorectal Surgery", "Oncology"],
    sub_specialties: ["Advanced Endoscopy", "Inflammatory Bowel Disease", "GI Motility"],
    referral_specialties: ["General Surgery", "Hepatology", "Oncology"],
    doctor_title: "Gastroenterologist", department_name: "Department of Gastroenterology", hospital_department: "Digestive Endoscopy & GI Center",
    search_keywords: ["stomach doctor", "gastric specialist", "digestive doctor", "endoscopy doctor", "colonoscopy doctor"],
    synonyms: ["Digestive Diseases", "Gastrointestinal Medicine", "GI Medicine"], abbreviations: ["GAST", "GI"],
    alternative_names: ["Medical Gastroenterology"], common_misspellings: ["gastroentrology", "gastroenterolgy"],
    ICD_related_terms: ["K20-K93", "K50", "K51"], SNOMED_related_terms: ["394584008"], LOINC_related_terms: ["18753-4"],
    medical_report_types: ["Endoscopy Reports", "Colonoscopy Reports", "ERCP Reports", "Fecal Calprotectin Reports"],
    supported_document_types: ["PDF", "JPG", "PNG"], is_clinical: true, is_diagnostic: true, is_surgical: false, is_laboratory: false, is_imaging: false, is_primary_care: false, is_subspecialty: false, is_active: true
  },
  // 5. Pulmonology
  {
    id: "SPEC-PULM-005", parent_id: null, specialty_code: "PULM", specialty_name: "Pulmonology",
    official_name: "Pulmonary & Respiratory Medicine", display_name: "Pulmonology",
    category: ["CLINICAL", "DIAGNOSTIC"], specialty_level: 1, parent_specialty: null,
    description: "Prevention, diagnosis, and treatment of respiratory tract and lung parenchyma disorders.",
    clinical_scope: ["Asthma", "COPD", "Pneumonia", "Interstitial Lung Disease", "Pleural diseases", "Pulmonary Hypertension"],
    organ_system: ["Respiratory System"], body_system: ["Respiratory System"],
    anatomical_regions: ["Trachea", "Bronchi", "Lungs", "Alveoli", "Pleura", "Mediastinum"],
    primary_functions: ["Gas Exchange (O2/CO2)", "Ventilation", "Acid-Base Balance"],
    common_conditions: ["Bronchial Asthma", "COPD", "Pneumonia", "Bronchiectasis", "Pleural Effusion"],
    major_diseases: ["Idiopathic Pulmonary Fibrosis", "Pulmonary Embolism", "Pulmonary Hypertension", "Lung Cancer", "ARDS"],
    common_symptoms: ["Chronic Cough", "Shortness of Breath (Dyspnea)", "Wheezing", "Coughing Blood (Hemoptysis)", "Pleurisy"],
    diagnostic_tests: ["Spirometry / PFT", "FeNO Test", "Flexible Bronchoscopy", "6-Minute Walk Test"],
    laboratory_tests: ["Arterial Blood Gas (ABG)", "Sputum Culture & Gram Stain", "AFB Sputum / GeneXpert", "D-Dimer"],
    imaging_tests: ["Chest X-Ray", "HRCT Chest", "CT Pulmonary Angiography (CTPA)", "Thoracic Ultrasound"],
    procedures: ["Thoracentesis", "Chest Tube Insertion", "Bronchoalveolar Lavage (BAL)"],
    treatments: ["Inhaled Bronchodilators & Steroids", "Oxygen Therapy", "BiPAP/CPAP", "Antifibrotics"],
    medications_or_drug_classes: ["Beta-2 Agonists", "Inhaled Corticosteroids", "LAMA", "Antifibrotics"],
    surgical_procedures: [], emergency_conditions: ["Massive Pulmonary Embolism", "Tension Pneumothorax", "Status Asthmaticus", "ARDS"],
    related_specialties: ["Cardiothoracic Surgery", "Critical Care", "Allergology", "Sleep Medicine"],
    sub_specialties: ["Interventional Pulmonology", "Sleep Medicine", "Pulmonary Hypertension"],
    referral_specialties: ["Cardiothoracic Surgery", "Oncology", "Infectious Disease"],
    doctor_title: "Pulmonologist", department_name: "Department of Pulmonology", hospital_department: "Pulmonary Medicine & Respiratory ICU",
    search_keywords: ["lung doctor", "chest specialist", "asthma doctor", "breathing specialist", "cough doctor"],
    synonyms: ["Pulmonary Medicine", "Respiratory Medicine", "Pneumology", "Chest Medicine"], abbreviations: ["PULM", "RESP"],
    alternative_names: ["Chest Diseases & Pulmonology"], common_misspellings: ["pulmonolgy", "pulmanology"],
    ICD_related_terms: ["J40-J47", "J12-J18", "I26"], SNOMED_related_terms: ["418112009"], LOINC_related_terms: ["18754-2"],
    medical_report_types: ["PFT Reports", "Chest X-Rays", "HRCT Chest Scans", "ABG Reports"],
    supported_document_types: ["PDF", "JPG", "PNG", "DICOM"], is_clinical: true, is_diagnostic: true, is_surgical: false, is_laboratory: false, is_imaging: true, is_primary_care: false, is_subspecialty: false, is_active: true
  },
  // 6. Endocrinology
  {
    id: "SPEC-ENDO-006", parent_id: null, specialty_code: "ENDO", specialty_name: "Endocrinology",
    official_name: "Endocrinology, Diabetes & Metabolism", display_name: "Endocrinology",
    category: ["CLINICAL", "DIAGNOSTIC"], specialty_level: 1, parent_specialty: null,
    description: "Management of endocrine glands, hormonal synthesis, and metabolic diseases.",
    clinical_scope: ["Diabetes Mellitus", "Thyroid disorders", "Pituitary & Adrenal disorders", "Osteoporosis", "PCOS", "Lipid disorders"],
    organ_system: ["Endocrine System"], body_system: ["Endocrine & Metabolic System"],
    anatomical_regions: ["Thyroid", "Pituitary", "Adrenals", "Pancreatic Islets", "Parathyroids", "Gonads"],
    primary_functions: ["Hormone Regulation", "Glucose Homeostasis", "Metabolism Modulation", "Calcium Homeostasis"],
    common_conditions: ["Type 1 & 2 Diabetes", "Hypothyroidism", "Hyperthyroidism", "Osteoporosis", "PCOS"],
    major_diseases: ["Cushing's Syndrome", "Addison's Disease", "Pituitary Adenoma", "Diabetic Ketoacidosis (DKA)", "Pheochromocytoma"],
    common_symptoms: ["Excessive Thirst/Urination", "Weight Fluctuations", "Chronic Fatigue", "Heat/Cold Intolerance", "Hirsutism"],
    diagnostic_tests: ["OGTT Glucose Tolerance", "Dexamethasone Suppression", "Thyroid Ultrasound", "DEXA Bone Scan"],
    laboratory_tests: ["HbA1c", "Fasting Glucose", "Thyroid Panel (TSH, FT3, FT4)", "Serum Cortisol", "PTH", "Vitamin D"],
    imaging_tests: ["Thyroid Scintigraphy", "Pituitary MRI", "Adrenal CT", "DEXA Scan"],
    procedures: ["Continuous Glucose Monitoring (CGM)", "Insulin Pump Management", "Thyroid FNAC Guidance"],
    treatments: ["Insulin Therapy", "Oral Hypoglycemics (Metformin, SGLT2i)", "Levothyroxine", "Antithyroid Drugs"],
    medications_or_drug_classes: ["Insulins", "GLP-1 Agonists", "SGLT2 Inhibitors", "Levothyroxine"],
    surgical_procedures: [], emergency_conditions: ["DKA", "Hyperosmolar Hyperglycemic State", "Myxedema Coma", "Thyroid Storm", "Adrenal Crisis"],
    related_specialties: ["Internal Medicine", "Gynecology", "Nephrology", "Cardiology"],
    sub_specialties: ["Diabetology", "Pediatric Endocrinology", "Metabolic Bone Diseases"],
    referral_specialties: ["General Surgery (Endocrine)", "Neurosurgery", "Ophthalmology"],
    doctor_title: "Endocrinologist", department_name: "Department of Endocrinology", hospital_department: "Endocrinology & Diabetes Center",
    search_keywords: ["diabetes doctor", "sugar specialist", "thyroid doctor", "hormone specialist", "weight doctor"],
    synonyms: ["Endocrine Medicine", "Diabetes & Metabolism"], abbreviations: ["ENDO"],
    alternative_names: ["Clinical Endocrinology"], common_misspellings: ["endocrynology", "endocrinolgy"],
    ICD_related_terms: ["E10-E14", "E00-E07", "E20-E35"], SNOMED_related_terms: ["394583001"], LOINC_related_terms: ["18755-9"],
    medical_report_types: ["HbA1c Panels", "Thyroid Profiles", "DEXA Scans", "Hormone Level Reports"],
    supported_document_types: ["PDF", "JPG", "PNG"], is_clinical: true, is_diagnostic: true, is_surgical: false, is_laboratory: false, is_imaging: false, is_primary_care: false, is_subspecialty: false, is_active: true
  }
];

console.log("Complete specialty definitions initialized. Ready to generate 58 records.");
