import mongoose from 'mongoose';
import dotenv from 'dotenv';
import path from 'path';
import { fileURLToPath } from 'url';
import Institution from '../models/Institution.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

dotenv.config({ path: path.join(__dirname, '../.env') });

const connectDB = async () => {
  try {
    await mongoose.connect(process.env.MONGO_URI);
    console.log('MongoDB Connected for Expansion...');
  } catch (err) {
    console.error(err.message);
    process.exit(1);
  }
};

const hospitalData = [
  { name: "Apollo Hospital, Greams Road", city: "Chennai", state: "Tamil Nadu", type: "Hospital", ownership: "Private" },
  { name: "Fortis Memorial Research Institute (FMRI)", city: "Gurgaon", state: "Haryana", type: "Hospital", ownership: "Private" },
  { name: "Max Super Speciality Hospital, Saket", city: "Delhi", state: "Delhi", type: "Hospital", ownership: "Private" },
  { name: "Medanta - The Medicity", city: "Gurgaon", state: "Haryana", type: "Hospital", ownership: "Private" },
  { name: "Manipal Hospital, Old Airport Road", city: "Bangalore", state: "Karnataka", type: "Hospital", ownership: "Private" },
  { name: "Narayana Health City", city: "Bangalore", state: "Karnataka", type: "Hospital", ownership: "Private" },
  { name: "Sir H. N. Reliance Foundation Hospital", city: "Mumbai", state: "Maharashtra", type: "Hospital", ownership: "Private" },
  { name: "Kokilaben Dhirubhai Ambani Hospital", city: "Mumbai", state: "Maharashtra", type: "Hospital", ownership: "Private" },
  { name: "Artemis Hospital", city: "Gurgaon", state: "Haryana", type: "Hospital", ownership: "Private" },
  { name: "BLK-Max Super Speciality Hospital", city: "Delhi", state: "Delhi", type: "Hospital", ownership: "Private" },
  { name: "Gleneagles Global Health City", city: "Chennai", state: "Tamil Nadu", type: "Hospital", ownership: "Private" },
  { name: "Aster CMI Hospital", city: "Bangalore", state: "Karnataka", type: "Hospital", ownership: "Private" },
  { name: "Lilavati Hospital and Research Centre", city: "Mumbai", state: "Maharashtra", type: "Hospital", ownership: "Private" },
  { name: "Nanavati Max Super Speciality Hospital", city: "Mumbai", state: "Maharashtra", type: "Hospital", ownership: "Private" },
  { name: "Amrita Hospital", city: "Kochi", state: "Kerala", type: "Hospital", ownership: "Private" },
  { name: "MIOT International", city: "Chennai", state: "Tamil Nadu", type: "Hospital", ownership: "Private" },
  { name: "Ruby Hall Clinic", city: "Pune", state: "Maharashtra", type: "Hospital", ownership: "Private" },
  { name: "Jehangir Hospital", city: "Pune", state: "Maharashtra", type: "Hospital", ownership: "Private" },
  { name: "KIMS Hospital", city: "Trivandrum", state: "Kerala", type: "Hospital", ownership: "Private" },
  { name: "Care Hospitals, Banjara Hills", city: "Hyderabad", state: "Telangana", type: "Hospital", ownership: "Private" },
  { name: "Yashoda Hospitals, Somajiguda", city: "Hyderabad", state: "Telangana", type: "Hospital", ownership: "Private" },
  { name: "Continental Hospitals", city: "Hyderabad", state: "Telangana", type: "Hospital", ownership: "Private" },
  { name: "AMRI Hospitals, Salt Lake", city: "Kolkata", state: "West Bengal", type: "Hospital", ownership: "Private" },
  { name: "Peerless Hospital", city: "Kolkata", state: "West Bengal", type: "Hospital", ownership: "Private" },
  { name: "Apollo Multispeciality Hospitals", city: "Kolkata", state: "West Bengal", type: "Hospital", ownership: "Private" },
  { name: "Kalinga Hospital", city: "Bhubaneswar", state: "Odisha", type: "Hospital", ownership: "Private" },
  { name: "Care Hospitals, Chandrasekharpur", city: "Bhubaneswar", state: "Odisha", type: "Hospital", ownership: "Private" },
  { name: "Summit Digital Hospital", city: "Bhubaneswar", state: "Odisha", type: "Hospital", ownership: "Private" },
  { name: "SevenHills Hospital", city: "Mumbai", state: "Maharashtra", type: "Hospital", ownership: "Private" },
  { name: "Fortis Hospital, Bannerghatta Road", city: "Bangalore", state: "Karnataka", type: "Hospital", ownership: "Private" },
  { name: "Columbia Asia Referral Hospital", city: "Bangalore", state: "Karnataka", type: "Hospital", ownership: "Private" },
  { name: "Sakra World Hospital", city: "Bangalore", state: "Karnataka", type: "Hospital", ownership: "Private" },
  { name: "BGS Gleneagles Global Hospital", city: "Bangalore", state: "Karnataka", type: "Hospital", ownership: "Private" },
  { name: "Cloudnine Hospital, Jayanagar", city: "Bangalore", state: "Karnataka", type: "Hospital", ownership: "Private" },
  { name: "Rainbow Children's Hospital", city: "Hyderabad", state: "Telangana", type: "Hospital", ownership: "Private" },
  { name: "Sunshine Hospitals", city: "Hyderabad", state: "Telangana", type: "Hospital", ownership: "Private" },
  { name: "Apollo Health City, Jubilee Hills", city: "Hyderabad", state: "Telangana", type: "Hospital", ownership: "Private" },
  { name: "KIMS-Sunshine Hospitals", city: "Secunderabad", state: "Telangana", type: "Hospital", ownership: "Private" },
  { name: "AIG Hospitals", city: "Hyderabad", state: "Telangana", type: "Hospital", ownership: "Private" },
  { name: "Fortis Hospital, Mulund", city: "Mumbai", state: "Maharashtra", type: "Hospital", ownership: "Private" },
  { name: "S. L. Raheja Hospital", city: "Mumbai", state: "Maharashtra", type: "Hospital", ownership: "Private" },
  { name: "Wockhardt Hospitals, South Mumbai", city: "Mumbai", state: "Maharashtra", type: "Hospital", ownership: "Private" },
  { name: "Jaslok Hospital & Research Centre", city: "Mumbai", state: "Maharashtra", type: "Hospital", ownership: "Private" },
  { name: "Breach Candy Hospital", city: "Mumbai", state: "Maharashtra", type: "Hospital", ownership: "Private" },
  { name: "P. D. Hinduja National Hospital", city: "Mumbai", state: "Maharashtra", type: "Hospital", ownership: "Private" },
  { name: "Bombay Hospital & Medical Research Centre", city: "Mumbai", state: "Maharashtra", type: "Hospital", ownership: "Private" },
  { name: "Tata Memorial Hospital", city: "Mumbai", state: "Maharashtra", type: "Hospital", ownership: "Government" },
  { name: "Holy Family Hospital", city: "Mumbai", state: "Maharashtra", type: "Hospital", ownership: "Private" },
  { name: "Dr. L. H. Hiranandani Hospital", city: "Mumbai", state: "Maharashtra", type: "Hospital", ownership: "Private" },
  { name: "Fortis Escorts Heart Institute", city: "Delhi", state: "Delhi", type: "Hospital", ownership: "Private" },
  { name: "Indraprastha Apollo Hospital", city: "Delhi", state: "Delhi", type: "Hospital", ownership: "Private" },
  { name: "Sir Ganga Ram Hospital", city: "Delhi", state: "Delhi", type: "Hospital", ownership: "Private" },
  { name: "Moolchand Hospital", city: "Delhi", state: "Delhi", type: "Hospital", ownership: "Private" },
  { name: "St. Stephen's Hospital", city: "Delhi", state: "Delhi", type: "Hospital", ownership: "Private" },
  { name: "Holy Family Hospital, Okhla", city: "Delhi", state: "Delhi", type: "Hospital", ownership: "Private" },
  { name: "Primus Super Speciality Hospital", city: "Delhi", state: "Delhi", type: "Hospital", ownership: "Private" },
  { name: "Venkateshwar Hospital", city: "Delhi", state: "Delhi", type: "Hospital", ownership: "Private" },
  { name: "Action Cancer Hospital", city: "Delhi", state: "Delhi", type: "Hospital", ownership: "Private" },
  { name: "Dharamshila Narayana Superspeciality Hospital", city: "Delhi", state: "Delhi", type: "Hospital", ownership: "Private" },
  { name: "Metro Hospital & Cancer Institute", city: "Delhi", state: "Delhi", type: "Hospital", ownership: "Private" },
  { name: "Max Smart Super Speciality Hospital", city: "Delhi", state: "Delhi", type: "Hospital", ownership: "Private" },
  { name: "Fortis Hospital, Shalimar Bagh", city: "Delhi", state: "Delhi", type: "Hospital", ownership: "Private" },
  { name: "Manipal Hospital, Dwarka", city: "Delhi", state: "Delhi", type: "Hospital", ownership: "Private" },
  { name: "Batra Hospital & Medical Research Centre", city: "Delhi", state: "Delhi", type: "Hospital", ownership: "Private" },
  { name: "Pushpawati Singhania Hospital & Research Institute (PSRI Hospital)", city: "Delhi", state: "Delhi", type: "Hospital", ownership: "Private" },
  { name: "Sitaram Bhartia Institute of Science and Research", city: "Delhi", state: "Delhi", type: "Hospital", ownership: "Private" },
  { name: "Safdarjung Hospital", city: "Delhi", state: "Delhi", type: "Hospital", ownership: "Government" },
  { name: "Ram Manohar Lohia Hospital (RML)", city: "Delhi", state: "Delhi", type: "Hospital", ownership: "Government" },
  { name: "Lady Hardinge Medical College & Hospital", city: "Delhi", state: "Delhi", type: "Hospital", ownership: "Government" },
  { name: "Maulana Azad Medical College & Associated Hospitals", city: "Delhi", state: "Delhi", type: "Hospital", ownership: "Government" },
  { name: "Guru Teg Bahadur Hospital (GTB)", city: "Delhi", state: "Delhi", type: "Hospital", ownership: "Government" },
  { name: "Lok Nayak Jai Prakash Narayan Hospital (LNJP)", city: "Delhi", state: "Delhi", type: "Hospital", ownership: "Government" },
  { name: "Deen Dayal Upadhyay Hospital (DDU)", city: "Delhi", state: "Delhi", type: "Hospital", ownership: "Government" },
  { name: "G. B. Pant Hospital", city: "Delhi", state: "Delhi", type: "Hospital", ownership: "Government" },
  { name: "Sanjay Gandhi Memorial Hospital", city: "Delhi", state: "Delhi", type: "Hospital", ownership: "Government" },
  { name: "Dr. Baba Saheb Ambedkar Hospital", city: "Delhi", state: "Delhi", type: "Hospital", ownership: "Government" },
  { name: "Max Super Speciality Hospital, Mohali", city: "Mohali", state: "Punjab", type: "Hospital", ownership: "Private" },
  { name: "Fortis Hospital, Mohali", city: "Mohali", state: "Punjab", type: "Hospital", ownership: "Private" },
  { name: "Ivy Hospital", city: "Mohali", state: "Punjab", type: "Hospital", ownership: "Private" },
  { name: "Mayo Hospital", city: "Mohali", state: "Punjab", type: "Hospital", ownership: "Private" },
  { name: "Sohana Hospital", city: "Mohali", state: "Punjab", type: "Hospital", ownership: "Private" },
  { name: "Cloudnine Hospital, Mohali", city: "Mohali", state: "Punjab", type: "Hospital", ownership: "Private" },
  { name: "PGIMER (Post Graduate Institute of Medical Education and Research)", city: "Chandigarh", state: "Chandigarh", type: "Hospital", ownership: "Government" },
  { name: "Government Medical College and Hospital (GMCH 32)", city: "Chandigarh", state: "Chandigarh", type: "Hospital", ownership: "Government" },
  { name: "GMSH 16 (Government Multi Specialty Hospital)", city: "Chandigarh", state: "Chandigarh", type: "Hospital", ownership: "Government" },
  { name: "Fortis Escorts Hospital, Jaipur", city: "Jaipur", state: "Rajasthan", type: "Hospital", ownership: "Private" },
  { name: "Eternal Hospital (EHCC)", city: "Jaipur", state: "Rajasthan", type: "Hospital", ownership: "Private" },
  { name: "Narayana Multispeciality Hospital, Jaipur", city: "Jaipur", state: "Rajasthan", type: "Hospital", ownership: "Private" },
  { name: "Manipal Hospital, Jaipur", city: "Jaipur", state: "Rajasthan", type: "Hospital", ownership: "Private" },
  { name: "Apex Hospital", city: "Jaipur", state: "Rajasthan", type: "Hospital", ownership: "Private" },
  { name: "CK Birla Hospital (RBH)", city: "Jaipur", state: "Rajasthan", type: "Hospital", ownership: "Private" },
  { name: "SMS Hospital (Sawai Man Singh Hospital)", city: "Jaipur", state: "Rajasthan", type: "Hospital", ownership: "Government" },
  { name: "Santokba Durlabhji Memorial Hospital", city: "Jaipur", state: "Rajasthan", type: "Hospital", ownership: "Private" },
  { name: "Sahyadri Super Speciality Hospital", city: "Pune", state: "Maharashtra", type: "Hospital", ownership: "Private" },
  { name: "Noble Hospital", city: "Pune", state: "Maharashtra", type: "Hospital", ownership: "Private" },
  { name: "Inlaks & Budhrani Hospital", city: "Pune", state: "Maharashtra", type: "Hospital", ownership: "Private" },
  { name: "Deenanath Mangeshkar Hospital", city: "Pune", state: "Maharashtra", type: "Hospital", ownership: "Private" },
  { name: "Sassoon General Hospital", city: "Pune", state: "Maharashtra", type: "Hospital", ownership: "Government" },
  { name: "KEM Hospital, Pune", city: "Pune", state: "Maharashtra", type: "Hospital", ownership: "Private" },
  { name: "Aditya Birla Memorial Hospital", city: "Pune", state: "Maharashtra", type: "Hospital", ownership: "Private" },
  { name: "Jupiter Hospital, Pune", city: "Pune", state: "Maharashtra", type: "Hospital", ownership: "Private" },
  { name: "Manipal Hospital, Pune", city: "Pune", state: "Maharashtra", type: "Hospital", ownership: "Private" },
  { name: "H. V. Desai Eye Hospital", city: "Pune", state: "Maharashtra", type: "Hospital", ownership: "Private" },
  { name: "Sterling Hospital", city: "Ahmedabad", state: "Gujarat", type: "Hospital", ownership: "Private" },
  { name: "Zydus Hospital", city: "Ahmedabad", state: "Gujarat", type: "Hospital", ownership: "Private" },
  { name: "Shelby Hospital", city: "Ahmedabad", state: "Gujarat", type: "Hospital", ownership: "Private" },
  { name: "Apollo Hospital, Ahmedabad", city: "Ahmedabad", state: "Gujarat", type: "Hospital", ownership: "Private" },
  { name: "CIMS Hospital (Care Institute of Medical Sciences)", city: "Ahmedabad", state: "Gujarat", type: "Hospital", ownership: "Private" },
  { name: "KD Hospital (Kusum Dhirajlal Hospital)", city: "Ahmedabad", state: "Gujarat", type: "Hospital", ownership: "Private" },
  { name: "HCG Cancer Centre, Ahmedabad", city: "Ahmedabad", state: "Gujarat", type: "Hospital", ownership: "Private" },
  { name: "Sola Civil Hospital", city: "Ahmedabad", state: "Gujarat", type: "Hospital", ownership: "Government" },
  { name: "SVP Institute of Medical Sciences and Research", city: "Ahmedabad", state: "Gujarat", type: "Hospital", ownership: "Government" },
  { name: "Civil Hospital, Ahmedabad", city: "Ahmedabad", state: "Gujarat", type: "Hospital", ownership: "Government" },
  { name: "U. N. Mehta Institute of Cardiology", city: "Ahmedabad", state: "Gujarat", type: "Hospital", ownership: "Government" },
  { name: "Gujarat Cancer & Research Institute", city: "Ahmedabad", state: "Gujarat", type: "Hospital", ownership: "Government" },
  { name: "SIMS Hospital (SRM Institutes for Medical Science)", city: "Chennai", state: "Tamil Nadu", type: "Hospital", ownership: "Private" },
  { name: "Billroth Hospitals", city: "Chennai", state: "Tamil Nadu", type: "Hospital", ownership: "Private" },
  { name: "Dr. Rela Institute & Medical Centre", city: "Chennai", state: "Tamil Nadu", type: "Hospital", ownership: "Private" },
  { name: "Kauvery Hospital", city: "Chennai", state: "Tamil Nadu", type: "Hospital", ownership: "Private" },
  { name: "Vijaya Hospital", city: "Chennai", state: "Tamil Nadu", type: "Hospital", ownership: "Private" },
  { name: "Prashanth Super Speciality Hospital", city: "Chennai", state: "Tamil Nadu", type: "Hospital", ownership: "Private" },
  { name: "Frontier Lifeline Hospital", city: "Chennai", state: "Tamil Nadu", type: "Hospital", ownership: "Private" },
  { name: "Madras Medical Mission (MMM)", city: "Chennai", state: "Tamil Nadu", type: "Hospital", ownership: "Private" },
  { name: "Sankara Nethralaya", city: "Chennai", state: "Tamil Nadu", type: "Hospital", ownership: "Private" },
  { name: "Government General Hospital, Chennai", city: "Chennai", state: "Tamil Nadu", type: "Hospital", ownership: "Government" },
  { name: "Stanley Medical College & Hospital", city: "Chennai", state: "Tamil Nadu", type: "Hospital", ownership: "Government" },
  { name: "Kilpauk Medical College & Hospital", city: "Chennai", state: "Tamil Nadu", type: "Hospital", ownership: "Government" },
  { name: "Royapettah Hospital", city: "Chennai", state: "Tamil Nadu", type: "Hospital", ownership: "Government" },
  { name: "Government Children Hospital, Egmore", city: "Chennai", state: "Tamil Nadu", type: "Hospital", ownership: "Government" },
  { name: "Institute of Child Health and Hospital for Children", city: "Chennai", state: "Tamil Nadu", type: "Hospital", ownership: "Government" },
  { name: "Cancer Institute (WIA), Adyar", city: "Chennai", state: "Tamil Nadu", type: "Hospital", ownership: "Private" },
  { name: "Ganga Hospital", city: "Coimbatore", state: "Tamil Nadu", type: "Hospital", ownership: "Private" },
  { name: "KMCH (Kovai Medical Center and Hospital)", city: "Coimbatore", state: "Tamil Nadu", type: "Hospital", ownership: "Private" },
  { name: "PSG Hospitals", city: "Coimbatore", state: "Tamil Nadu", type: "Hospital", ownership: "Private" },
  { name: "Ramakrishna Hospital", city: "Coimbatore", state: "Tamil Nadu", type: "Hospital", ownership: "Private" },
  { name: "KG Hospital", city: "Coimbatore", state: "Tamil Nadu", type: "Hospital", ownership: "Private" },
  { name: "G. Kuppuswamy Naidu Memorial Hospital (GKNM)", city: "Coimbatore", state: "Tamil Nadu", type: "Hospital", ownership: "Private" },
  { name: "Coimbatore Medical College Hospital", city: "Coimbatore", state: "Tamil Nadu", type: "Hospital", ownership: "Government" },
  { name: "Meenakshi Mission Hospital and Research Centre", city: "Madurai", state: "Tamil Nadu", type: "Hospital", ownership: "Private" },
  { name: "Velammal Medical College Hospital", city: "Madurai", state: "Tamil Nadu", type: "Hospital", ownership: "Private" },
  { name: "Apollo Specialty Hospital, Madurai", city: "Madurai", state: "Tamil Nadu", type: "Hospital", ownership: "Private" },
  { name: "Government Rajaji Hospital", city: "Madurai", state: "Tamil Nadu", type: "Hospital", ownership: "Government" },
  { name: "Christian Medical College & Hospital (CMC Vellore)", city: "Vellore", state: "Tamil Nadu", type: "Hospital", ownership: "Private" },
  { name: "Narayana Medical College & Hospital", city: "Nellore", state: "Andhra Pradesh", type: "Hospital", ownership: "Private" },
  { name: "Apollo Hospitals, Visakhapatnam", city: "Visakhapatnam", state: "Andhra Pradesh", type: "Hospital", ownership: "Private" },
  { name: "SevenHills Hospital, Vizag", city: "Visakhapatnam", state: "Andhra Pradesh", type: "Hospital", ownership: "Private" },
  { name: "Care Hospitals, Visakhapatnam", city: "Visakhapatnam", state: "Andhra Pradesh", type: "Hospital", ownership: "Private" },
  { name: "King George Hospital (KGH)", city: "Visakhapatnam", state: "Andhra Pradesh", type: "Hospital", ownership: "Government" },
  { name: "Manipal Hospital, Vijayawada", city: "Vijayawada", state: "Andhra Pradesh", type: "Hospital", ownership: "Private" },
  { name: "Rainbow Children's Hospital, Vijayawada", city: "Vijayawada", state: "Andhra Pradesh", type: "Hospital", ownership: "Private" },
  { name: "Government General Hospital, Vijayawada", city: "Vijayawada", state: "Andhra Pradesh", type: "Hospital", ownership: "Government" },
  { name: "Ramesh Hospitals", city: "Vijayawada", state: "Andhra Pradesh", type: "Hospital", ownership: "Private" },
  { name: "Capital Hospital, Bhubaneswar", city: "Bhubaneswar", state: "Odisha", type: "Hospital", ownership: "Government" },
  { name: "AIIMS Bhubaneswar", city: "Bhubaneswar", state: "Odisha", type: "Hospital", ownership: "Government" },
  { name: "SUM Hospital", city: "Bhubaneswar", state: "Odisha", type: "Hospital", ownership: "Private" },
  { name: "KIMS Hospital, Bhubaneswar", city: "Bhubaneswar", state: "Odisha", type: "Hospital", ownership: "Private" },
  { name: "AMRI Hospitals, Bhubaneswar", city: "Bhubaneswar", state: "Odisha", type: "Hospital", ownership: "Private" },
  { name: "Care Hospitals, Bhubaneswar", city: "Bhubaneswar", state: "Odisha", type: "Hospital", ownership: "Private" },
  { name: "SCB Medical College & Hospital", city: "Cuttack", state: "Odisha", type: "Hospital", ownership: "Government" },
  { name: "Ashwini Hospital", city: "Cuttack", state: "Odisha", type: "Hospital", ownership: "Private" },
  { name: "Woodlands Multispeciality Hospital", city: "Kolkata", state: "West Bengal", type: "Hospital", ownership: "Private" },
  { name: "Belle Vue Clinic", city: "Kolkata", state: "West Bengal", type: "Hospital", ownership: "Private" },
  { name: "Ruby General Hospital", city: "Kolkata", state: "West Bengal", type: "Hospital", ownership: "Private" },
  { name: "Medica Superspecialty Hospital", city: "Kolkata", state: "West Bengal", type: "Hospital", ownership: "Private" },
  { name: "Fortis Hospital, Anandapur", city: "Kolkata", state: "West Bengal", type: "Hospital", ownership: "Private" },
  { name: "Desun Hospital", city: "Kolkata", state: "West Bengal", type: "Hospital", ownership: "Private" },
  { name: "RN Tagore International Institute of Cardiac Sciences", city: "Kolkata", state: "West Bengal", type: "Hospital", ownership: "Private" },
  { name: "B.M. Birla Heart Research Centre", city: "Kolkata", state: "West Bengal", type: "Hospital", ownership: "Private" },
  { name: "Calcutta Medical College & Hospital", city: "Kolkata", state: "West Bengal", type: "Hospital", ownership: "Government" },
  { name: "NRS Medical College & Hospital", city: "Kolkata", state: "West Bengal", type: "Hospital", ownership: "Government" },
  { name: "RG Kar Medical College & Hospital", city: "Kolkata", state: "West Bengal", type: "Hospital", ownership: "Government" },
  { name: "SSKM Hospital (IPGMER)", city: "Kolkata", state: "West Bengal", type: "Hospital", ownership: "Government" },
  { name: "Chittaranjan Seva Sadan", city: "Kolkata", state: "West Bengal", type: "Hospital", ownership: "Government" },
  { name: "Medanta Lucknow", city: "Lucknow", state: "Uttar Pradesh", type: "Hospital", ownership: "Private" },
  { name: "Apollo Medics Super Speciality Hospital", city: "Lucknow", state: "Uttar Pradesh", type: "Hospital", ownership: "Private" },
  { name: "Sahara Hospital", city: "Lucknow", state: "Uttar Pradesh", type: "Hospital", ownership: "Private" },
  { name: "Sanjay Gandhi Post Graduate Institute of Medical Sciences (SGPGI)", city: "Lucknow", state: "Uttar Pradesh", type: "Hospital", ownership: "Government" },
  { name: "King George's Medical University (KGMU)", city: "Lucknow", state: "Uttar Pradesh", type: "Hospital", ownership: "Government" },
  { name: "Dr. Ram Manohar Lohia Institute of Medical Sciences (RMLIMS)", city: "Lucknow", state: "Uttar Pradesh", type: "Hospital", ownership: "Government" },
  { name: "Era's Lucknow Medical College & Hospital", city: "Lucknow", state: "Uttar Pradesh", type: "Hospital", ownership: "Private" },
  { name: "T. S. Misra Medical College & Hospital", city: "Lucknow", state: "Uttar Pradesh", type: "Hospital", ownership: "Private" },
  { name: "Regency Hospital", city: "Kanpur", state: "Uttar Pradesh", type: "Hospital", ownership: "Private" },
  { name: "KMC Digital Hospital", city: "Kanpur", state: "Uttar Pradesh", type: "Hospital", ownership: "Private" },
  { name: "LPS Institute of Cardiology", city: "Kanpur", state: "Uttar Pradesh", type: "Hospital", ownership: "Government" },
  { name: "Hallet Hospital (GSVM Medical College)", city: "Kanpur", state: "Uttar Pradesh", type: "Hospital", ownership: "Government" },
  { name: "Jaypee Hospital", city: "Noida", state: "Uttar Pradesh", type: "Hospital", ownership: "Private" },
  { name: "Fortis Hospital, Noida", city: "Noida", state: "Uttar Pradesh", type: "Hospital", ownership: "Private" },
  { name: "Max Super Speciality Hospital, Noida", city: "Noida", state: "Uttar Pradesh", type: "Hospital", ownership: "Private" },
  { name: "Metro Hospital & Heart Institute, Noida", city: "Noida", state: "Uttar Pradesh", type: "Hospital", ownership: "Private" },
  { name: "Kailash Hospital & Heart Institute", city: "Noida", state: "Uttar Pradesh", type: "Hospital", ownership: "Private" },
  { name: "Sharda Hospital", city: "Greater Noida", state: "Uttar Pradesh", type: "Hospital", ownership: "Private" },
  { name: "Yashoda Super Speciality Hospital", city: "Ghaziabad", state: "Uttar Pradesh", type: "Hospital", ownership: "Private" },
  { name: "Max Super Speciality Hospital, Vaishali", city: "Ghaziabad", state: "Uttar Pradesh", type: "Hospital", ownership: "Private" },
  { name: "Sarvodaya Hospital", city: "Faridabad", state: "Haryana", type: "Hospital", ownership: "Private" },
  { name: "Asian Institute of Medical Sciences", city: "Faridabad", state: "Haryana", type: "Hospital", ownership: "Private" },
  { name: "Fortis Escorts Hospital, Faridabad", city: "Faridabad", state: "Haryana", type: "Hospital", ownership: "Private" },
  { name: "Amrita Hospital, Faridabad", city: "Faridabad", state: "Haryana", type: "Hospital", ownership: "Private" },
  { name: "Paras Hospital", city: "Gurgaon", state: "Haryana", type: "Hospital", ownership: "Private" },
  { name: "Columbia Asia Hospital, Palam Vihar", city: "Gurgaon", state: "Haryana", type: "Hospital", ownership: "Private" },
  { name: "W Pratiksha Hospital", city: "Gurgaon", state: "Haryana", type: "Hospital", ownership: "Private" },
  { name: "CK Birla Hospital for Women", city: "Gurgaon", state: "Haryana", type: "Hospital", ownership: "Private" },
  { name: "Cloudnine Hospital, Gurgaon", city: "Gurgaon", state: "Haryana", type: "Hospital", ownership: "Private" },
  { name: "Signature Hospital", city: "Gurgaon", state: "Haryana", type: "Hospital", ownership: "Private" },
  { name: "Fortis Hospital, Mohali", city: "Chandigarh", state: "Punjab", type: "Hospital", ownership: "Private" },
  { name: "Max Hospital, Mohali", city: "Chandigarh", state: "Punjab", type: "Hospital", ownership: "Private" },
  { name: "Landmark Hospital", city: "Chandigarh", state: "Chandigarh", type: "Hospital", ownership: "Private" },
  { name: "Mukat Hospital + Heart Institute", city: "Chandigarh", state: "Chandigarh", type: "Hospital", ownership: "Private" },
  { name: "Chaitanya Hospital", city: "Chandigarh", state: "Chandigarh", type: "Hospital", ownership: "Private" },
  { name: "Eden Critical Care Hospital", city: "Chandigarh", state: "Chandigarh", type: "Hospital", ownership: "Private" },
  { name: "Healing Hospital", city: "Chandigarh", state: "Chandigarh", type: "Hospital", ownership: "Private" },
  { name: "Silver Oaks Hospital", city: "Mohali", state: "Punjab", type: "Hospital", ownership: "Private" },
  { name: "DMC Hospital (Dayanand Medical College)", city: "Ludhiana", state: "Punjab", type: "Hospital", ownership: "Private" },
  { name: "CMC Hospital (Christian Medical College)", city: "Ludhiana", state: "Punjab", type: "Hospital", ownership: "Private" },
  { name: "Fortis Hospital, Ludhiana", city: "Ludhiana", state: "Punjab", type: "Hospital", ownership: "Private" },
  { name: "SPS Hospital", city: "Ludhiana", state: "Punjab", type: "Hospital", ownership: "Private" },
  { name: "Deep Hospital", city: "Ludhiana", state: "Punjab", type: "Hospital", ownership: "Private" },
  { name: "Global Hospital", city: "Ludhiana", state: "Punjab", type: "Hospital", ownership: "Private" },
  { name: "Hero DMC Heart Institute", city: "Ludhiana", state: "Punjab", type: "Hospital", ownership: "Private" },
  { name: "Apollo Cradle & Children’s Hospital", city: "Amritsar", state: "Punjab", type: "Hospital", ownership: "Private" },
  { name: "Fortis Escorts Hospital, Amritsar", city: "Amritsar", state: "Punjab", type: "Hospital", ownership: "Private" },
  { name: "Amandeep Hospital", city: "Amritsar", state: "Punjab", type: "Hospital", ownership: "Private" },
  { name: "Nayyar Hospital", city: "Amritsar", state: "Punjab", type: "Hospital", ownership: "Private" },
  { name: "Government Medical College & Hospital, Amritsar", city: "Amritsar", state: "Punjab", type: "Hospital", ownership: "Government" },
  { name: "Shri Guru Ram Das Institute of Medical Sciences & Research", city: "Amritsar", state: "Punjab", type: "Hospital", ownership: "Private" },
  { name: "Choithram Hospital and Research Centre", city: "Indore", state: "Madhya Pradesh", type: "Hospital", ownership: "Private" },
  { name: "Bombay Hospital Indore", city: "Indore", state: "Madhya Pradesh", type: "Hospital", ownership: "Private" },
  { name: "CHL Hospital", city: "Indore", state: "Madhya Pradesh", type: "Hospital", ownership: "Private" },
  { name: "Medanta Hospital, Indore", city: "Indore", state: "Madhya Pradesh", type: "Hospital", ownership: "Private" },
  { name: "Apollo Hospitals, Indore", city: "Indore", state: "Madhya Pradesh", type: "Hospital", ownership: "Private" },
  { name: "Shalby Hospital, Indore", city: "Indore", state: "Madhya Pradesh", type: "Hospital", ownership: "Private" },
  { name: "MY Hospital (Maharaja Yeshwantrao Hospital)", city: "Indore", state: "Madhya Pradesh", type: "Hospital", ownership: "Government" },
  { name: "Bansal Hospital", city: "Bhopal", state: "Madhya Pradesh", type: "Hospital", ownership: "Private" },
  { name: "L.N. Medical College & J.K. Hospital", city: "Bhopal", state: "Madhya Pradesh", type: "Hospital", ownership: "Private" },
  { name: "Chirayu Health & Medicare", city: "Bhopal", state: "Madhya Pradesh", type: "Hospital", ownership: "Private" },
  { name: "Peoples Hospital", city: "Bhopal", state: "Madhya Pradesh", type: "Hospital", ownership: "Private" },
  { name: "Hamidia Hospital", city: "Bhopal", state: "Madhya Pradesh", type: "Hospital", ownership: "Government" },
  { name: "AIIMS Bhopal", city: "Bhopal", state: "Madhya Pradesh", type: "Hospital", ownership: "Government" },
  { name: "Noble Hospital, Bhopal", city: "Bhopal", state: "Madhya Pradesh", type: "Hospital", ownership: "Private" },
  { name: "Sahyadri Hospital", city: "Nashik", state: "Maharashtra", type: "Hospital", ownership: "Private" },
  { name: "Wockhardt Hospitals, Nashik", city: "Nashik", state: "Maharashtra", type: "Hospital", ownership: "Private" },
  { name: "Apollo Hospitals, Nashik", city: "Nashik", state: "Maharashtra", type: "Hospital", ownership: "Private" },
  { name: "Six Sigma Hospital", city: "Nashik", state: "Maharashtra", type: "Hospital", ownership: "Private" },
  { name: "Magnum Heart Institute", city: "Nashik", state: "Maharashtra", type: "Hospital", ownership: "Private" },
  { name: "Nashik Civil Hospital", city: "Nashik", state: "Maharashtra", type: "Hospital", ownership: "Government" },
  { name: "Wockhardt Hospitals, Nagpur", city: "Nagpur", state: "Maharashtra", type: "Hospital", ownership: "Private" },
  { name: "Orange City Hospital & Research Institute", city: "Nagpur", state: "Maharashtra", type: "Hospital", ownership: "Private" },
  { name: "Alexis Multispeciality Hospital", city: "Nagpur", state: "Maharashtra", type: "Hospital", ownership: "Private" },
  { name: "Care Hospital, Nagpur", city: "Nagpur", state: "Maharashtra", type: "Hospital", ownership: "Private" },
  { name: "Kingsway Hospitals", city: "Nagpur", state: "Maharashtra", type: "Hospital", ownership: "Private" },
  { name: "Nagpur Civil Hospital", city: "Nagpur", state: "Maharashtra", type: "Hospital", ownership: "Government" },
  { name: "Government Medical College and Hospital, Nagpur", city: "Nagpur", state: "Maharashtra", type: "Hospital", ownership: "Government" },
  { name: "AIIMS Nagpur", city: "Nagpur", state: "Maharashtra", type: "Hospital", ownership: "Government" },
  { name: "KIMS Hospital, Secunderabad", city: "Secunderabad", state: "Telangana", type: "Hospital", ownership: "Private" },
  { name: "Apollo Hospital, Secunderabad", city: "Secunderabad", state: "Telangana", type: "Hospital", ownership: "Private" },
  { name: "Yashoda Hospital, Secunderabad", city: "Secunderabad", state: "Telangana", type: "Hospital", ownership: "Private" },
  { name: "Sunshine Hospital, Secunderabad", city: "Secunderabad", state: "Telangana", type: "Hospital", ownership: "Private" },
  { name: "Star Hospitals", city: "Hyderabad", state: "Telangana", type: "Hospital", ownership: "Private" },
  { name: "Medicover Hospitals, Madhapur", city: "Hyderabad", state: "Telangana", type: "Hospital", ownership: "Private" },
  { name: "Omni Hospitals", city: "Hyderabad", state: "Telangana", type: "Hospital", ownership: "Private" },
  { name: "Virinchi Hospitals", city: "Hyderabad", state: "Telangana", type: "Hospital", ownership: "Private" },
  { name: "NIMS (Nizam's Institute of Medical Sciences)", city: "Hyderabad", state: "Telangana", type: "Hospital", ownership: "Government" },
  { name: "Osmania General Hospital", city: "Hyderabad", state: "Telangana", type: "Hospital", ownership: "Government" },
  { name: "Gandhi Hospital", city: "Secunderabad", state: "Telangana", type: "Hospital", ownership: "Government" },
  { name: "Basavatarakam Indo American Cancer Hospital", city: "Hyderabad", state: "Telangana", type: "Hospital", ownership: "Private" },
  { name: "L. V. Prasad Eye Institute (LVPEI)", city: "Hyderabad", state: "Telangana", type: "Hospital", ownership: "Private" },
  { name: "Manipal Hospital, Goa", city: "Goa", state: "Goa", type: "Hospital", ownership: "Private" },
  { name: "Healthway Hospital", city: "Goa", state: "Goa", type: "Hospital", ownership: "Private" },
  { name: "Victor Hospital", city: "Goa", state: "Goa", type: "Hospital", ownership: "Private" },
  { name: "Goa Medical College and Hospital", city: "Bambolim", state: "Goa", type: "Hospital", ownership: "Government" },
  { name: "Aster Medcity", city: "Kochi", state: "Kerala", type: "Hospital", ownership: "Private" },
  { name: "Rajagiri Hospital", city: "Kochi", state: "Kerala", type: "Hospital", ownership: "Private" },
  { name: "VPS Lakeshore Hospital", city: "Kochi", state: "Kerala", type: "Hospital", ownership: "Private" },
  { name: "Medical Trust Hospital", city: "Kochi", state: "Kerala", type: "Hospital", ownership: "Private" },
  { name: "Renai Medicity", city: "Kochi", state: "Kerala", type: "Hospital", ownership: "Private" },
  { name: "Sunrise Hospital", city: "Kochi", state: "Kerala", type: "Hospital", ownership: "Private" },
  { name: "Baby Memorial Hospital", city: "Calicut", state: "Kerala", type: "Hospital", ownership: "Private" },
  { name: "Aster MIMS", city: "Calicut", state: "Kerala", type: "Hospital", ownership: "Private" },
  { name: "Meitra Hospital", city: "Calicut", state: "Kerala", type: "Hospital", ownership: "Private" },
  { name: "Starcare Hospital", city: "Calicut", state: "Kerala", type: "Hospital", ownership: "Private" },
  { name: "Government Medical College, Kozhikode", city: "Calicut", state: "Kerala", type: "Hospital", ownership: "Government" },
  { name: "Sree Chitra Tirunal Institute for Medical Sciences and Technology", city: "Trivandrum", state: "Kerala", type: "Hospital", ownership: "Government" },
  { name: "Government Medical College, Thiruvananthapuram", city: "Trivandrum", state: "Kerala", type: "Hospital", ownership: "Government" },
  { name: "Cosmopolitan Hospital", city: "Trivandrum", state: "Kerala", type: "Hospital", ownership: "Private" },
  { name: "Ananthapuri Hospitals and Research Institute", city: "Trivandrum", state: "Kerala", type: "Hospital", ownership: "Private" },
  { name: "S. U. T. Hospital", city: "Trivandrum", state: "Kerala", type: "Hospital", ownership: "Private" },
  { name: "G. G. Hospital", city: "Trivandrum", state: "Kerala", type: "Hospital", ownership: "Private" },
  { name: "NIMS Medicity", city: "Trivandrum", state: "Kerala", type: "Hospital", ownership: "Private" },
  { name: "Believers Church Medical College Hospital", city: "Thiruvalla", state: "Kerala", type: "Hospital", ownership: "Private" },
  { name: "Pushpagiri Medical College Hospital", city: "Thiruvalla", state: "Kerala", type: "Hospital", ownership: "Private" },
  { name: "Muthoot Healthcare", city: "Kozhencherry", state: "Kerala", type: "Hospital", ownership: "Private" },
  { name: "Travancore Medicity", city: "Kollam", state: "Kerala", type: "Hospital", ownership: "Private" },
  { name: "N. S. Memorial Institute of Medical Sciences", city: "Kollam", state: "Kerala", type: "Hospital", ownership: "Private" },
  { name: "Bishop Benziger Hospital", city: "Kollam", state: "Kerala", type: "Hospital", ownership: "Private" },
  { name: "Medicity Hospital, Guwahati", city: "Guwahati", state: "Assam", type: "Hospital", ownership: "Private" },
  { name: "Apollo Hospitals, Guwahati", city: "Guwahati", state: "Assam", type: "Hospital", ownership: "Private" },
  { name: "Narayana Superspeciality Hospital, Guwahati", city: "Guwahati", state: "Assam", type: "Hospital", ownership: "Private" },
  { name: "GNRC Hospitals", city: "Guwahati", state: "Assam", type: "Hospital", ownership: "Private" },
  { name: "Health City Hospital", city: "Guwahati", state: "Assam", type: "Hospital", ownership: "Private" },
  { name: "Guwahati Medical College and Hospital", city: "Guwahati", state: "Assam", type: "Hospital", ownership: "Government" },
  { name: "Assam Medical College and Hospital", city: "Dibrugarh", state: "Assam", type: "Hospital", ownership: "Government" },
  { name: "Silchar Medical College and Hospital", city: "Silchar", state: "Assam", type: "Hospital", ownership: "Government" },
  { name: "Indira Gandhi Children's Hospital", city: "Kabul", state: "International-Sync", type: "Hospital", ownership: "Government" },
  { name: "Fortis Hospital, Bannerghatta", city: "Bangalore", state: "Karnataka", type: "Hospital", ownership: "Private" },
  { name: "Apollo Specialty Hospital, OMR", city: "Chennai", state: "Tamil Nadu", type: "Hospital", ownership: "Private" },
  { name: "Max Hospital, Gurgaon", city: "Gurgaon", state: "Haryana", type: "Hospital", ownership: "Private" },
  { name: "Fortis Escorts Hospital, Dehradun", city: "Dehradun", state: "Uttarakhand", type: "Hospital", ownership: "Private" },
  { name: "Max Super Speciality Hospital, Dehradun", city: "Dehradun", state: "Uttarakhand", type: "Hospital", ownership: "Private" },
  { name: "Doon Hospital", city: "Dehradun", state: "Uttarakhand", type: "Hospital", ownership: "Government" },
  { name: "AIIMS Rishikesh", city: "Rishikesh", state: "Uttarakhand", type: "Hospital", ownership: "Government" },
  { name: "Jolly Grant Hospital (HIHT)", city: "Dehradun", state: "Uttarakhand", type: "Hospital", ownership: "Private" },
  { name: "Synergy Institute of Medical Sciences", city: "Dehradun", state: "Uttarakhand", type: "Hospital", ownership: "Private" },
  { name: "Velridge Hospital", city: "Dehradun", state: "Uttarakhand", type: "Hospital", ownership: "Private" },
  { name: "Graph Era Hospital", city: "Dehradun", state: "Uttarakhand", type: "Hospital", ownership: "Private" },
  { name: "Fortis Hospital, Ludhiana", city: "Ludhiana", state: "Punjab", type: "Hospital", ownership: "Private" },
  { name: "Deepak Hospital", city: "Ludhiana", state: "Punjab", type: "Hospital", ownership: "Private" },
  { name: "Pancham Hospital", city: "Ludhiana", state: "Punjab", type: "Hospital", ownership: "Private" },
  { name: "Satguru Partap Singh Hospitals (SPS)", city: "Ludhiana", state: "Punjab", type: "Hospital", ownership: "Private" },
  { name: "Sigma Hospital", city: "Ludhiana", state: "Punjab", type: "Hospital", ownership: "Private" },
  { name: "Rishi Hospital", city: "Ludhiana", state: "Punjab", type: "Hospital", ownership: "Private" },
  { name: "Patiala Civil Hospital", city: "Patiala", state: "Punjab", type: "Hospital", ownership: "Government" },
  { name: "Rajindra Hospital", city: "Patiala", state: "Punjab", type: "Hospital", ownership: "Government" },
  { name: "Columbia Asia Hospital, Patiala", city: "Patiala", state: "Punjab", type: "Hospital", ownership: "Private" },
  { name: "Amar Hospital", city: "Patiala", state: "Punjab", type: "Hospital", ownership: "Private" },
  { name: "Vardhman Hospital", city: "Patiala", state: "Punjab", type: "Hospital", ownership: "Private" },
  { name: "Apex Hospital, Patiala", city: "Patiala", state: "Punjab", type: "Hospital", ownership: "Private" },
  { name: "Fortis Hospital, Kangra", city: "Kangra", state: "Himachal Pradesh", type: "Hospital", ownership: "Private" },
  { name: "Indira Gandhi Medical College, Shimla", city: "Shimla", state: "Himachal Pradesh", type: "Hospital", ownership: "Government" },
  { name: "Dr. Rajendra Prasad Government Medical College", city: "Kangra", state: "Himachal Pradesh", type: "Hospital", ownership: "Government" },
  { name: "Tanda Medical College", city: "Kangra", state: "Himachal Pradesh", type: "Hospital", ownership: "Government" },
  { name: "Zonal Hospital, Dharamshala", city: "Dharamshala", state: "Himachal Pradesh", type: "Hospital", ownership: "Government" },
  { name: "Shree Balaji Hospital", city: "Kangra", state: "Himachal Pradesh", type: "Hospital", ownership: "Private" },
  { name: "Vivekanand Medical Institute", city: "Palampur", state: "Himachal Pradesh", type: "Hospital", ownership: "Private" },
  { name: "Metro Hospital, Faridabad", city: "Faridabad", state: "Haryana", type: "Hospital", ownership: "Private" },
  { name: "SSB Hospital", city: "Faridabad", state: "Haryana", type: "Hospital", ownership: "Private" },
  { name: "QRG Health City", city: "Faridabad", state: "Haryana", type: "Hospital", ownership: "Private" },
  { name: "Accord Superspeciality Hospital", city: "Faridabad", state: "Haryana", type: "Hospital", ownership: "Private" },
  { name: "Sunflag Hospital", city: "Faridabad", state: "Haryana", type: "Hospital", ownership: "Private" },
  { name: "Arsh Superspeciality Hospital", city: "Faridabad", state: "Haryana", type: "Hospital", ownership: "Private" },
  { name: "Fortis Hospital, Amritsar", city: "Amritsar", state: "Punjab", type: "Hospital", ownership: "Private" },
  { name: "Parkash Hospital", city: "Amritsar", state: "Punjab", type: "Hospital", ownership: "Private" },
  { name: "Uppal Hospital", city: "Amritsar", state: "Punjab", type: "Hospital", ownership: "Private" },
  { name: "Hartej Hospital", city: "Amritsar", state: "Punjab", type: "Hospital", ownership: "Private" },
  { name: "Jivan Jot Hospital", city: "Amritsar", state: "Punjab", type: "Hospital", ownership: "Private" },
  { name: "KD Hospital", city: "Amritsar", state: "Punjab", type: "Hospital", ownership: "Private" },
  { name: "Amandeep Hospital & Clinics", city: "Amritsar", state: "Punjab", type: "Hospital", ownership: "Private" },
  { name: "Apex Hospital, Amritsar", city: "Amritsar", state: "Punjab", type: "Hospital", ownership: "Private" },
  { name: "Satyam Hospital", city: "Jalandhar", state: "Punjab", type: "Hospital", ownership: "Private" },
  { name: "Sacred Heart Hospital", city: "Jalandhar", state: "Punjab", type: "Hospital", ownership: "Private" },
  { name: "SGL Charitable Hospital", city: "Jalandhar", state: "Punjab", type: "Hospital", ownership: "Private" },
  { name: "Tagore Hospital", city: "Jalandhar", state: "Punjab", type: "Hospital", ownership: "Private" },
  { name: "PIMS Jalandhar (Punjab Institute of Medical Sciences)", city: "Jalandhar", state: "Punjab", type: "Hospital", ownership: "Private" },
  { name: "Capitol Hospital", city: "Jalandhar", state: "Punjab", type: "Hospital", ownership: "Private" },
  { name: "Shrimann Superspeciality Hospital", city: "Jalandhar", state: "Punjab", type: "Hospital", ownership: "Private" },
  { name: "Star Hospital, Jalandhar", city: "Jalandhar", state: "Punjab", type: "Hospital", ownership: "Private" },
  { name: "Oxford Hospital", city: "Jalandhar", state: "Punjab", type: "Hospital", ownership: "Private" },
  { name: "Gulab Devi Hospital", city: "Jalandhar", state: "Punjab", type: "Hospital", ownership: "Private" },
  { name: "Fortis Escorts, Faridabad", city: "Faridabad", state: "Haryana", type: "Hospital", ownership: "Private" },
  { name: "Artemis Health Institute", city: "Gurgaon", state: "Haryana", type: "Hospital", ownership: "Private" },
  { name: "Privat Hospital", city: "Gurgaon", state: "Haryana", type: "Hospital", ownership: "Private" },
  { name: "Aryan Hospital", city: "Gurgaon", state: "Haryana", type: "Hospital", ownership: "Private" },
  { name: "Mayom Hospital", city: "Gurgaon", state: "Haryana", type: "Hospital", ownership: "Private" },
  { name: "Vikas Hospital", city: "Gurgaon", state: "Haryana", type: "Hospital", ownership: "Private" },
  { name: "Neelkanth Hospital", city: "Gurgaon", state: "Haryana", type: "Hospital", ownership: "Private" },
  { name: "Park Hospital", city: "Gurgaon", state: "Haryana", type: "Hospital", ownership: "Private" },
  { name: "Sanjivani Hospital", city: "Gurgaon", state: "Haryana", type: "Hospital", ownership: "Private" },
  { name: "Lifeline Hospital", city: "Gurgaon", state: "Haryana", type: "Hospital", ownership: "Private" },
  { name: "Sheetla Hospital", city: "Gurgaon", state: "Haryana", type: "Hospital", ownership: "Private" },
  { name: "Sunrise Hospital, Gurgaon", city: "Gurgaon", state: "Haryana", type: "Hospital", ownership: "Private" },
  { name: "Global Hospital, Gurgaon", city: "Gurgaon", state: "Haryana", type: "Hospital", ownership: "Private" },
  { name: "Miracles Apollo Cradle", city: "Gurgaon", state: "Haryana", type: "Hospital", ownership: "Private" },
  { name: "Fortis La Femme", city: "Delhi", state: "Delhi", type: "Hospital", ownership: "Private" },
  { name: "Rosewalk Hospital", city: "Delhi", state: "Delhi", type: "Hospital", ownership: "Private" },
  { name: "Aakash Healthcare Super Speciality Hospital", city: "Delhi", state: "Delhi", type: "Hospital", ownership: "Private" },
  { name: "Rockland Hospital", city: "Delhi", state: "Delhi", type: "Hospital", ownership: "Private" },
  { name: "Maharaja Agrasen Hospital", city: "Delhi", state: "Delhi", type: "Hospital", ownership: "Private" },
  { name: "Jaipur Golden Hospital", city: "Delhi", state: "Delhi", type: "Hospital", ownership: "Private" },
  { name: "Bhagwati Hospital", city: "Delhi", state: "Delhi", type: "Hospital", ownership: "Private" },
  { name: "Brahm Shakti Hospital", city: "Delhi", state: "Delhi", type: "Hospital", ownership: "Private" },
  { name: "Saroj Super Speciality Hospital", city: "Delhi", state: "Delhi", type: "Hospital", ownership: "Private" },
  { name: "Sri Balaji Action Medical Institute", city: "Delhi", state: "Delhi", type: "Hospital", ownership: "Private" },
  { name: "Kalra Hospital", city: "Delhi", state: "Delhi", type: "Hospital", ownership: "Private" },
  { name: "Tirath Ram Shah Hospital", city: "Delhi", state: "Delhi", type: "Hospital", ownership: "Private" },
  { name: "Kasturba Hospital", city: "Delhi", state: "Delhi", type: "Hospital", ownership: "Government" },
  { name: "Girdhari Lal Maternity Hospital", city: "Delhi", state: "Delhi", type: "Hospital", ownership: "Government" },
  { name: "Rajan Babu Institute of Pulmonary Medicine", city: "Delhi", state: "Delhi", type: "Hospital", ownership: "Government" },
  { name: "Hindu Rao Hospital", city: "Delhi", state: "Delhi", type: "Hospital", ownership: "Government" },
  { name: "Aruna Asaf Ali Hospital", city: "Delhi", state: "Delhi", type: "Hospital", ownership: "Government" },
  { name: "Lal Bahadur Shastri Hospital", city: "Delhi", state: "Delhi", type: "Hospital", ownership: "Government" },
  { name: "Jag Pravesh Chandra Hospital", city: "Delhi", state: "Delhi", type: "Hospital", ownership: "Government" },
  { name: "Dr. Hedgewar Arogya Sansthan", city: "Delhi", state: "Delhi", type: "Hospital", ownership: "Government" },
  { name: "Chacha Nehru Bal Chikitsalaya", city: "Delhi", state: "Delhi", type: "Hospital", ownership: "Government" },
  { name: "Acharya Shree Bhikshu Hospital", city: "Delhi", state: "Delhi", type: "Hospital", ownership: "Government" },
  { name: "Bhagwan Mahavir Hospital", city: "Delhi", state: "Delhi", type: "Hospital", ownership: "Government" },
  { name: "Babu Jagjivan Ram Memorial Hospital", city: "Delhi", state: "Delhi", type: "Hospital", ownership: "Government" },
  { name: "Rao Tula Ram Memorial Hospital", city: "Delhi", state: "Delhi", type: "Hospital", ownership: "Government" },
  { name: "Deep Chand Bandhu Hospital", city: "Delhi", state: "Delhi", type: "Hospital", ownership: "Government" },
  { name: "Burari Hospital", city: "Delhi", state: "Delhi", type: "Hospital", ownership: "Government" },
  { name: "Ambedkar Nagar Hospital", city: "Delhi", state: "Delhi", type: "Hospital", ownership: "Government" },
  { name: "Indira Gandhi Hospital, Dwarka", city: "Delhi", state: "Delhi", type: "Hospital", ownership: "Government" },
];

const seed = async () => {
  await connectDB();

  try {
    const institutions = hospitalData.map(h => ({
      ...h,
      verificationStatus: 'Verified',
      isActive: true
    }));

    console.log(`Prepared ${institutions.length} additional hospitals. Adding to registry...`);
    await Institution.insertMany(institutions);

    console.log('Expansion Node Synchronization Complete!');
    process.exit();
  } catch (err) {
    console.error('Expansion Error:', err);
    process.exit(1);
  }
};

seed();
