import React, { useState } from 'react';
import Sidebar from '../common/Sidebar';
import Navbar from '../common/Navbar';
import { Home, Mail, Clock, Save, Camera, Globe, ShieldCheck as ShieldCheckIcon } from 'lucide-react';
import { toast } from 'react-hot-toast';
import useStore from '../../store/useStore';

const HospitalSettings = () => {
  const { theme } = useStore();

  return (
    <div className={`flex min-h-screen transition-colors duration-500 text-left ${theme === 'dark' ? 'bg-[#050505] text-zinc-300' : 'bg-[#F8FAFC] text-slate-600'}`}>
      <Sidebar role="admin" />
      <div className="flex-1 flex flex-col overflow-hidden relative">
        <Navbar />
        <main className="flex-1 overflow-y-auto p-6 space-y-10 custom-scrollbar relative z-10">
          <div className="max-w-4xl mx-auto space-y-8">

            <header className="flex justify-between items-end">
              <div className="text-left">
                <h1 className={`text-3xl font-black uppercase tracking-tight ${theme === 'dark' ? 'text-white' : 'text-slate-800'}`}>Hospital Configuration</h1>
                <p className="text-slate-500 font-medium mt-1">Update institution identity and contact protocols</p>
              </div>
            </header>

            <div className="grid grid-cols-1 lg:grid-cols-3 gap-10">

               <div className="lg:col-span-1 space-y-6">
                  <div className={`p-8 rounded-[40px] border shadow-sm text-center relative overflow-hidden transition-all duration-500 ${theme === 'dark' ? 'bg-[#0E0E12]/90 border-white/5' : 'bg-white border-slate-100'}`}>
                     <div className={`w-24 h-24 mx-auto flex items-center justify-center rounded-[32px] mb-6 border-2 border-dashed cursor-pointer group transition-all ${theme === 'dark' ? 'bg-white/5 border-white/10 text-blue-400' : 'bg-blue-50 border-blue-200 text-blue-600'}`}>
                        <Camera size={32} className="group-hover:scale-110 transition-transform"/>
                     </div>
                     <h2 className={`text-xl font-black uppercase tracking-tighter ${theme === 'dark' ? 'text-white' : 'text-slate-800'}`}>Institution Logo</h2>
                     <p className="text-xs text-slate-400 font-bold mt-2">Recommended: 512x512 PNG</p>
                     <button className={`mt-6 w-full py-3 rounded-2xl text-[10px] font-black uppercase transition-all ${theme === 'dark' ? 'bg-white/5 text-zinc-500 hover:text-white' : 'bg-slate-50 text-slate-400 hover:bg-slate-100'}`}>Upload New Logo</button>
                  </div>

                  <div className="bg-blue-600 p-8 rounded-[40px] shadow-xl shadow-blue-500/20 text-white space-y-4">
                     <div className="w-10 h-10 bg-white/20 rounded-xl flex items-center justify-center"><ShieldCheckIcon size={20}/></div>
                     <h3 className="font-black uppercase tracking-tight">System Identity</h3>
                     <p className="text-xs text-blue-100 font-medium leading-relaxed italic">"These details will appear on all digital prescriptions, bills, and referral letters generated by the platform."</p>
                  </div>
               </div>

               <div className={`lg:col-span-2 p-10 rounded-[40px] border shadow-sm space-y-8 transition-all duration-500 ${theme === 'dark' ? 'bg-[#0E0E12]/90 border-white/5' : 'bg-white border-slate-100'}`}>
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
                     <div className="space-y-2 text-left">
                        <label className="text-[10px] font-black text-zinc-500 uppercase tracking-widest ml-1">Hospital Name</label>
                        <input type="text" defaultValue="Medi Consult Multi-Speciality" className={`w-full p-4 border rounded-2xl font-bold text-sm outline-none transition-all ${theme === 'dark' ? 'bg-white/5 border-white/10 text-white focus:border-blue-500' : 'bg-slate-50 border-slate-200 text-slate-700 focus:ring-2 focus:ring-blue-100'}`} />
                     </div>
                     <div className="space-y-2 text-left">
                        <label className="text-[10px] font-black text-zinc-500 uppercase tracking-widest ml-1">Hospital Code</label>
                        <input type="text" defaultValue="HOSP2024" disabled className={`w-full p-4 border rounded-2xl font-black text-sm outline-none cursor-not-allowed ${theme === 'dark' ? 'bg-zinc-800 border-white/5 text-zinc-500' : 'bg-slate-100 border-slate-100 text-slate-400'}`} />
                     </div>
                     <div className="space-y-2 text-left">
                        <label className="text-[10px] font-black text-zinc-500 uppercase tracking-widest ml-1">Contact Phone</label>
                        <input type="text" defaultValue="+91 80 4455 6677" className={`w-full p-4 border rounded-2xl font-bold text-sm outline-none transition-all ${theme === 'dark' ? 'bg-white/5 border-white/10 text-white focus:border-blue-500' : 'bg-slate-50 border-slate-200 text-slate-700'}`} />
                     </div>
                     <div className="space-y-2 text-left">
                        <label className="text-[10px] font-black text-zinc-500 uppercase tracking-widest ml-1">Institutional Email</label>
                        <input type="email" defaultValue="care@mediconsult.com" className={`w-full p-4 border rounded-2xl font-bold text-sm outline-none transition-all ${theme === 'dark' ? 'bg-white/5 border-white/10 text-white focus:border-blue-500' : 'bg-slate-50 border-slate-200 text-slate-700'}`} />
                     </div>
                  </div>

                  <div className="space-y-2 text-left">
                     <label className="text-[10px] font-black text-zinc-500 uppercase tracking-widest ml-1">Physical Address</label>
                     <textarea className={`w-full p-4 border rounded-2xl font-medium text-sm min-h-[100px] outline-none transition-all ${theme === 'dark' ? 'bg-white/5 border-white/10 text-white focus:border-blue-500' : 'bg-slate-50 border-slate-200 text-slate-700'}`}>45, Health Tech Park, Sector 12, Whitefield, Bangalore - 560066</textarea>
                  </div>

                  <div className={`pt-8 border-t flex justify-end gap-4 ${theme === 'dark' ? 'border-white/5' : 'border-slate-50'}`}>
                     <button className={`px-10 py-4 rounded-2xl font-black text-xs uppercase tracking-widest transition-all ${theme === 'dark' ? 'bg-white/5 text-zinc-500 hover:text-white' : 'bg-slate-50 text-slate-400 hover:bg-slate-100'}`}>Discard</button>
                     <button onClick={() => toast.success("Hospital profile updated")} className="px-12 py-4 bg-blue-600 text-white rounded-2xl font-black text-xs shadow-xl shadow-blue-500/20 flex items-center gap-2 hover:bg-blue-700 transition-all uppercase tracking-widest active:scale-95">
                        <Save size={16}/> Save Changes
                     </button>
                  </div>
               </div>

            </div>
          </div>
        </main>
      </div>
    </div>
  );
};

export default HospitalSettings;
